"""Generate the map registry module and map-selection XML from maps.json.

maps.json is the single source of truth (produced by extract_maps.py). This
replaces the 2020 mod's 339 hand-written `setupXxx()` handlers and 339
hand-written XML buttons, which had to be kept in sync by hand.

Run:  python tools/extract/gen_registry.py
"""
import html
import json
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAPS = ROOT / "tools" / "extract" / "maps.json"
LUA_OUT = ROOT / "src" / "fd" / "data" / "maps.lua"
XML_OUT = ROOT / "src" / "entry" / "Custom Board.9e2fe8.xml"

BANNER = "Generated by tools/extract/gen_registry.py from maps.json; do not edit by hand."

# The scroll grid is 1660 wide with 515-wide cells and 18 spacing, so three
# cells per row; the 2020 file's hand-tuned heights match rows*373 + 18 exactly.
PER_ROW, ROW_H, GRID_PAD = 3, 373, 18

PANELS = [
    ("formula_d", "mapSelectionFD", "openMapSelectionFD", "ThumbD"),
    ("formula_de", "mapSelectionFDe", "openMapSelectionFDe", "ThumbDe"),
    ("custom", "mapSelectionCustom", "openMapSelectionCustom", "ThumbCustom"),
]


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def xml_attr(s):
    # Values were read raw out of the 2020 XML, so decode entities first to
    # avoid double-escaping names like "Indy &amp; GP".
    return html.escape(html.unescape(s), quote=True)


def gen_lua(maps):
    L = [f"-- {BANNER}", "", "local Maps = {}", "", "Maps.list = {"]
    for m in maps:
        L.append(
            "    {{ id = {}, name = {}, key = {}, category = {}, url = {}, thumb = {} }},".format(
                lua_str(m["id"]), lua_str(m["name"]), lua_str(m["key"]),
                lua_str(m["category"]), lua_str(m["url"]), lua_str(m["thumb"] or ""),
            )
        )
    L += [
        "}",
        "",
        "Maps.byId = {}",
        "for _, m in ipairs(Maps.list) do",
        "    Maps.byId[m.id] = m",
        "end",
        "",
        "--- All maps in one category, in display order.",
        "function Maps.inCategory(category)",
        "    local out = {}",
        "    for _, m in ipairs(Maps.list) do",
        "        if m.category == category then",
        "            out[#out + 1] = m",
        "        end",
        "    end",
        "    return out",
        "end",
        "",
        "--- Image URL for a map id, or nil if the id is unknown.",
        "function Maps.urlOf(id)",
        "    local m = Maps.byId[id]",
        "    return m and m.url or nil",
        "end",
        "",
        "return Maps",
        "",
    ]
    return "\n".join(L)


def gen_xml(maps, defaults_block, menu_block):
    out = [f"<!-- {BANNER} -->", "", defaults_block.strip(), "", menu_block.strip(), ""]
    used = {m["category"] for m in maps}
    panels = [p for p in PANELS if p[0] in used]

    for category, panel_id, _, _ in panels:
        rows = [m for m in maps if m["category"] == category]
        height = math.ceil(len(rows) / PER_ROW) * ROW_H + GRID_PAD
        out += [
            f'<Panel id="{panel_id}" class="mapSelectPanel" active="false">',
            '    <VerticalScrollView class="mapSelectorVertScroll">',
            f'        <GridLayout padding="0 0 8 3" spacing="18 18" height="{height}"'
            ' cellsize="515 355" childAlignment="UpperCenter">',
        ]
        for m in rows:
            img = (
                f'<Image class="mapImage" image="{xml_attr(m["thumb"])}"></Image>'
                if m["thumb"] else ""
            )
            out.append(
                f'            <Button class="mapButton" onClick="selectMap({m["id"]})"'
                f' text="{xml_attr(m["name"])}">{img}</Button>'
            )
        out += [
            "        </GridLayout>",
            "    </VerticalScrollView>",
            '    <Panel rotation="-30 0 0" position="-105 385 240" width="1600">',
            '        <GridLayout padding="0 0 8 3" spacing="18 18" cellsize="515 355"'
            ' childAlignment="UpperCenter">',
        ]
        for tab_cat, _, tab_click, tab_img in panels:
            # The active tab shows at full opacity, the others dimmed.
            tint = "rgba(1,1,1,1)" if tab_cat == category else "rgba(1,1,1,0.5)"
            out.append(
                f'            <Button color="rgba(0,0,0,0)"><Image class="mapTypeImage"'
                f' onClick="{tab_click}" image="{tab_img}" color="{tint}"></Image></Button>'
            )
        out += [
            "        </GridLayout>",
            "    </Panel>",
            '    <Button id="closeButton" width="60" height="60" rectAlignment="UpperRight"'
            ' color="#990000" textColor="#FFFFFF" text="X" onClick="returnToMenu"'
            ' tooltip="Click here to return to main menu." tooltipPosition="Above"></Button>',
            "</Panel>",
            "",
        ]
    return "\n".join(out)


def main():
    maps = json.loads(MAPS.read_text(encoding="utf-8"))
    original = (ROOT / "reference" / "original-2020" / "Custom Board.9e2fe8.xml").read_text(
        encoding="utf-8", errors="replace"
    )
    # Reuse the 2020 <Defaults> styling and main menu panel verbatim; only the
    # generated map lists below them are ours.
    defaults_block = original[original.index("<Defaults>"):original.index("</Defaults>") + len("</Defaults>")]
    menu_start = original.index('<Panel class="fullBoardPanel">')
    menu_block = original[menu_start:original.index('<Panel id="mapSelectionFD"')]

    LUA_OUT.parent.mkdir(parents=True, exist_ok=True)
    XML_OUT.parent.mkdir(parents=True, exist_ok=True)
    LUA_OUT.write_text(gen_lua(maps), encoding="utf-8")
    XML_OUT.write_text(gen_xml(maps, defaults_block, menu_block), encoding="utf-8")

    print(f"{len(maps)} maps")
    print(f"  -> {LUA_OUT.relative_to(ROOT)}  ({LUA_OUT.stat().st_size:,} bytes)")
    print(f"  -> {XML_OUT.relative_to(ROOT)}  ({XML_OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
