"""Generate the Lua track modules from the track files.

The mod cannot read JSON off disk, so every tracks/<id>.json becomes a Lua
module the entry scripts can require. Positions stay in image pixels, as
docs/track-format.md says -- the board tile is movable, so they are converted
to world space at load.

Run:  python tools/extract/gen_tracks.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TRACKS = ROOT / "tracks"
OUT = ROOT / "src" / "fd" / "data" / "tracks"

BANNER = "Generated by tools/extract/gen_tracks.py from tracks/{}.json -- do not edit by hand."


def lit(v):
    """A Lua literal for an id or sector: codes are strings, a fresh scan's ids numbers."""
    return '"%s"' % v if isinstance(v, str) else str(v)


def neighbours(pairs):
    """{id: [ids]} from the pairs in a <id>.adjacency.json, both ways round."""
    near = {}
    for a, b in pairs:
        near.setdefault(a, []).append(b)
        near.setdefault(b, []).append(a)
    return {k: sorted(v) for k, v in near.items()}


def lua_track(track, near=None):
    L = [f"-- {BANNER.format(track['id'])}", "",
         "local T = {}", "",
         f'T.id = "{track["id"]}"',
         f'T.name = "{track["name"]}"',
         f'T.ruleset = "{track["ruleset"]}"',
         f'T.lanes = {track["lanes"]}',
         f'T.laps = {track["laps"]}',
         f'T.image = {{ width = {track["image"]["width"]}, height = {track["image"]["height"]} }}',
         "",
         "-- The outside edge of the road, in running order (image pixels), as",
         "-- the pieces where it was found -- gaps are where it was not.",
         "T.outer = {"]
    for piece in track.get("outer", []):
        L.append("    { " + ", ".join(f"{{ {x}, {y} }}" for x, y in piece) + " },")
    L += ["}", "",
          "-- id, x, y (image pixels), facing in degrees, lane, then the spaces",
          "-- this one leads to. An id is the space's code, <lane>.<sector>.<n>:",
          "-- lane i/m/o (inside, middle, outside of the lap), sector cN or sN,",
          "-- n counting from 0 at the sector's leading edge. `corner`",
          "-- is the corner a space lies inside; `fixed` marks links set by hand",
          "-- in the editor, which are never recomputed.",
          "T.spaces = {"]
    for s in track["spaces"]:
        nxt = ", ".join(lit(n) for n in s["next"])
        extra = ""
        if s.get("corner"):
            extra += ", corner = {}".format(s["corner"])
        if s.get("fixed"):
            extra += ", fixed = true"
        L.append("    {{ id = {}, pos = {{ {}, {} }}, rot = {}, lane = {}, sector = {}, next = {{ {} }}{} }},".format(
            lit(s["id"]), s["pos"][0], s["pos"][1], s["rot"], s["lane"], lit(s["sector"]), nxt, extra))
    L += ["}", "",
          "-- Corners in running order from the start. A space inside one carries",
          "-- its id (`corner` above). `stops` is how many times a car must stop",
          "-- inside it; `long` and `short` are the ways through it the board",
          "-- prints in green and red.",
          "T.corners = {"]
    for c in track.get("corners", []):
        stops = c["stops"] if c.get("stops") is not None else "nil"
        name = ', name = "{}"'.format(c["name"]) if c.get("name") else ""
        ways = ", long = {}, short = {}".format(c["long"], c["short"]) if c.get("long") else ""
        L.append("    {{ id = {}, stops = {}{}{} }},".format(c["id"], stops, ways, name))
    L += ["}", "",
          "-- The starting grid, pole first.",
          "T.start = {" + "".join(" " + lit(v) + "," for v in track.get("start", [])).rstrip(",") + (" }" if track.get("start") else "}"),
          "",
          "-- The finish line, as the space just past it in each lane: a move",
          "-- that steps onto one of these has crossed the line.",
          "T.finish = { line = {" + "".join(" " + lit(v) + "," for v in track.get("finish", {}).get("line", [])).rstrip(",") + (" } }" if track.get("finish", {}).get("line", []) else "} }"),
          "",
          "-- The spaces touching each one, in any direction and whatever the",
          "-- arrows say: from tracks/<id>.adjacency.json (find_adjacency.py).",
          "-- A car ending its move rolls for a collision with each car in one.",
          "T.near = {"]
    for sid in sorted(near or {}):
        L.append("    [{}] = {{ {} }},".format(lit(sid), ", ".join(lit(n) for n in near[sid])))
    L += ["}", "",
          "T.byId = {}",
          "for _, s in ipairs(T.spaces) do",
          "    T.byId[s.id] = s",
          "end",
          "",
          "return T", ""]
    return "\n".join(L)


def main():
    # tracks/<id>.json only: <id>.arrows.json beside it is a reading of the
    # board's arrows, which find_arrows.py turns into the track's links, and
    # <id>.adjacency.json the spaces that touch, read in below.
    files = sorted(f for f in TRACKS.glob("*.json") if f.stem.count(".") == 0)
    if not files:
        sys.exit("no track files in tracks/")
    OUT.mkdir(parents=True, exist_ok=True)
    for f in files:
        track = json.loads(f.read_text(encoding="utf-8"))
        adjacency = TRACKS / f"{track['id']}.adjacency.json"
        near = None
        if adjacency.exists():
            near = neighbours(json.loads(adjacency.read_text(encoding="utf-8"))["pairs"])
        path = OUT / f"{track['id']}.lua"
        path.write_text(lua_track(track, near), encoding="utf-8")
        print(f"{track['name']}: {len(track['spaces'])} spaces, {len(near or {})} with neighbours"
              f" -> {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
