"""Generate the gear dice rotation values from dice_faces.json.

The six gear dice in the Big Box mod are custom models with no rotation values,
so TTS cannot say what was rolled. dice_faces.json records, for every face, the
number printed on it and the direction it points in the mesh. This turns each
direction into the Euler rotation that puts that face on top, which is what
`setRotationValues` wants.

Run:  python tools/extract/gen_dice.py
"""
import json
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "tools" / "extract" / "dice_faces.json"
OUT = ROOT / "src" / "fd" / "data" / "dice.lua"

BANNER = "Generated by tools/extract/gen_dice.py from dice_faces.json -- do not edit by hand."


def to_unity(v):
    # TTS imports OBJ files with the X axis mirrored (Unity is left-handed).
    return (-v[0], v[1], v[2])


def euler_for_up(u):
    """Euler angles (degrees, Unity Z-X-Y order) that rotate local `u` to world up.

    Unity composes rotations as R = Ry * Rx * Rz. With y = 0, first roll about Z
    to bring `u` into the Y-Z plane, then pitch about X to stand it upright.
    """
    ux, uy, uz = u
    z = math.atan2(ux, uy)
    vy = math.hypot(ux, uy)
    x = math.atan2(-uz, vy)
    return (math.degrees(x) % 360, 0.0, math.degrees(z) % 360)


def rotate(euler, v):
    """Apply a Unity Euler rotation to a vector -- used to self-check the output."""
    x, y, z = (math.radians(a) for a in euler)
    vx, vy, vz = v
    # Z
    vx, vy = vx * math.cos(z) - vy * math.sin(z), vx * math.sin(z) + vy * math.cos(z)
    # X
    vy, vz = vy * math.cos(x) - vz * math.sin(x), vy * math.sin(x) + vz * math.cos(x)
    # Y
    vx, vz = vx * math.cos(y) + vz * math.sin(y), -vx * math.sin(y) + vz * math.cos(y)
    return vx, vy, vz


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    L = [f"-- {BANNER}", "",
         "-- Rotation values for the six gear dice, indexed by gear.",
         "-- Pass one list to object.setRotationValues().", "",
         "local Dice = {}", ""]
    for gear in sorted(k for k in data if not k.startswith("_")):
        die = data[gear]
        L.append(f"Dice[{gear}] = {{")
        for face in die["faces"]:
            u = to_unity(face["up"])
            n = math.sqrt(sum(c * c for c in u))
            u = tuple(c / n for c in u)
            e = euler_for_up(u)
            up = rotate(e, u)
            assert abs(up[1] - 1) < 1e-6, (gear, face, up)
            L.append("    {{ value = {}, rotation = {{ {:.2f}, {:.2f}, {:.2f} }} }},".format(face["value"], *e))
        L.append("}")
        L.append("")
    L.append("-- Nickname of each gear die in the save, indexed by gear.")
    L.append("Dice.names = {")
    for gear in sorted(k for k in data if not k.startswith("_")):
        L.append(f'    "{data[gear]["name"]}",')
    L += ["}", "", "return Dice", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"  -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
