"""Generate the Lua track modules from the track files.

The mod cannot read JSON off disk, so every tracks/<id>.json becomes a Lua
module the entry scripts can require. Positions stay in image pixels, as
docs/track-format.md says -- the board tile is movable, so they are converted
to world space at load.

Run:  python tools/extract/gen_tracks.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TRACKS = ROOT / "tracks"
OUT = ROOT / "src" / "fd" / "data" / "tracks"

BANNER = "Generated by tools/extract/gen_tracks.py from tracks/{}.json -- do not edit by hand."


def lua_track(track):
    L = [f"-- {BANNER.format(track['id'])}", "",
         "local T = {}", "",
         f'T.id = "{track["id"]}"',
         f'T.name = "{track["name"]}"',
         f'T.ruleset = "{track["ruleset"]}"',
         f'T.lanes = {track["lanes"]}',
         f'T.laps = {track["laps"]}',
         f'T.image = {{ width = {track["image"]["width"]}, height = {track["image"]["height"]} }}',
         "",
         "-- The outside edge of the road, in running order (image pixels), as",
         "-- the pieces where it was found -- gaps are where it was not.",
         "T.outer = {"]
    for piece in track.get("outer", []):
        L.append("    { " + ", ".join(f"{{ {x}, {y} }}" for x, y in piece) + " },")
    L += ["}", "",
          "-- id, x, y (image pixels), facing in degrees, lane, then the spaces",
          "-- this one leads to. Ids run lane by lane in running order. `corner`",
          "-- is the corner a space lies inside; `fixed` marks links set by hand",
          "-- in the editor, which are never recomputed.",
          "T.spaces = {"]
    for s in track["spaces"]:
        nxt = ", ".join(str(n) for n in s["next"])
        extra = ""
        if s.get("corner"):
            extra += ", corner = {}".format(s["corner"])
        if s.get("fixed"):
            extra += ", fixed = true"
        L.append("    {{ id = {}, pos = {{ {}, {} }}, rot = {}, lane = {}, sector = {}, next = {{ {} }}{} }},".format(
            s["id"], s["pos"][0], s["pos"][1], s["rot"], s["lane"], s["sector"], nxt, extra))
    L += ["}", "",
          "-- Corners in running order from the start. A space inside one carries",
          "-- its id (`corner` above). `stops` is how many times a car must stop",
          "-- inside it; `long` and `short` are the ways through it the board",
          "-- prints in green and red.",
          "T.corners = {"]
    for c in track.get("corners", []):
        stops = c["stops"] if c.get("stops") is not None else "nil"
        name = ', name = "{}"'.format(c["name"]) if c.get("name") else ""
        ways = ", long = {}, short = {}".format(c["long"], c["short"]) if c.get("long") else ""
        L.append("    {{ id = {}, stops = {}{}{} }},".format(c["id"], stops, ways, name))
    L += ["}", "",
          "T.byId = {}",
          "for _, s in ipairs(T.spaces) do",
          "    T.byId[s.id] = s",
          "end",
          "",
          "return T", ""]
    return "\n".join(L)


def main():
    # tracks/<id>.json only: <id>.arrows.json beside it is a reading of the
    # board's arrows, which find_arrows.py turns into the track's links.
    files = sorted(f for f in TRACKS.glob("*.json") if f.stem.count(".") == 0)
    if not files:
        sys.exit("no track files in tracks/")
    OUT.mkdir(parents=True, exist_ok=True)
    for f in files:
        track = json.loads(f.read_text(encoding="utf-8"))
        path = OUT / f"{track['id']}.lua"
        path.write_text(lua_track(track), encoding="utf-8")
        print(f"{track['name']}: {len(track['spaces'])} spaces -> {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
