-- Generated by tools/extract/gen_dice.py from dice_faces.json -- do not edit by hand.

-- Rotation values for the six gear dice, indexed by gear.
-- Pass one list to object.setRotationValues().

local Dice = {}

Dice[1] = {
    { value = 1, rotation = { 54.74, 0.00, 125.26 } },
    { value = 2, rotation = { 305.26, 0.00, 125.26 } },
    { value = 1, rotation = { 0.00, 0.00, 250.53 } },
    { value = 2, rotation = { 0.00, 0.00, 0.00 } },
}

Dice[2] = {
    { value = 3, rotation = { 270.00, 0.00, 0.00 } },
    { value = 3, rotation = { 0.00, 0.00, 270.00 } },
    { value = 4, rotation = { 0.00, 0.00, 90.00 } },
    { value = 4, rotation = { 90.00, 0.00, 0.00 } },
    { value = 4, rotation = { 0.00, 0.00, 0.00 } },
    { value = 2, rotation = { 0.00, 0.00, 180.00 } },
}

Dice[3] = {
    { value = 5, rotation = { 35.26, 0.00, 315.00 } },
    { value = 8, rotation = { 35.26, 0.00, 45.00 } },
    { value = 6, rotation = { 324.74, 0.00, 45.00 } },
    { value = 7, rotation = { 324.74, 0.00, 315.00 } },
    { value = 7, rotation = { 35.26, 0.00, 225.00 } },
    { value = 6, rotation = { 35.26, 0.00, 135.00 } },
    { value = 8, rotation = { 324.74, 0.00, 135.00 } },
    { value = 4, rotation = { 324.74, 0.00, 225.00 } },
}

Dice[4] = {
    { value = 9, rotation = { 296.28, 0.00, 0.00 } },
    { value = 10, rotation = { 63.72, 0.00, 180.00 } },
    { value = 7, rotation = { 313.83, 0.00, 130.61 } },
    { value = 9, rotation = { 313.83, 0.00, 229.39 } },
    { value = 12, rotation = { 0.28, 0.00, 180.00 } },
    { value = 7, rotation = { 359.72, 0.00, 0.00 } },
    { value = 8, rotation = { 343.82, 0.00, 62.34 } },
    { value = 11, rotation = { 343.82, 0.00, 297.66 } },
    { value = 11, rotation = { 16.18, 0.00, 242.34 } },
    { value = 8, rotation = { 16.18, 0.00, 117.66 } },
    { value = 12, rotation = { 46.17, 0.00, 310.61 } },
    { value = 10, rotation = { 46.17, 0.00, 49.39 } },
}

Dice[5] = {
    { value = 19, rotation = { 48.24, 0.00, 299.91 } },
    { value = 13, rotation = { 311.76, 0.00, 119.91 } },
    { value = 15, rotation = { 48.24, 0.00, 60.09 } },
    { value = 18, rotation = { 311.76, 0.00, 240.09 } },
    { value = 19, rotation = { 60.71, 0.00, 226.83 } },
    { value = 16, rotation = { 299.29, 0.00, 313.17 } },
    { value = 13, rotation = { 299.29, 0.00, 46.83 } },
    { value = 12, rotation = { 60.71, 0.00, 133.17 } },
    { value = 15, rotation = { 352.65, 0.00, 250.37 } },
    { value = 12, rotation = { 7.35, 0.00, 289.63 } },
    { value = 16, rotation = { 352.65, 0.00, 109.63 } },
    { value = 18, rotation = { 7.35, 0.00, 70.37 } },
    { value = 17, rotation = { 19.40, 0.00, 217.74 } },
    { value = 14, rotation = { 340.60, 0.00, 322.26 } },
    { value = 11, rotation = { 340.60, 0.00, 37.74 } },
    { value = 14, rotation = { 19.40, 0.00, 142.26 } },
    { value = 11, rotation = { 318.09, 0.00, 180.00 } },
    { value = 17, rotation = { 41.91, 0.00, 0.00 } },
    { value = 20, rotation = { 0.10, 0.00, 0.00 } },
    { value = 20, rotation = { 359.90, 0.00, 180.00 } },
}

Dice[6] = {
    { value = 25, rotation = { 342.00, 0.00, 58.28 } },
    { value = 26, rotation = { 18.00, 0.00, 238.28 } },
    { value = 27, rotation = { 342.00, 0.00, 121.72 } },
    { value = 22, rotation = { 342.00, 0.00, 238.28 } },
    { value = 21, rotation = { 0.00, 0.00, 180.00 } },
    { value = 30, rotation = { 0.00, 0.00, 0.00 } },
    { value = 24, rotation = { 18.00, 0.00, 301.72 } },
    { value = 23, rotation = { 54.00, 0.00, 301.72 } },
    { value = 28, rotation = { 306.00, 0.00, 121.72 } },
    { value = 29, rotation = { 54.00, 0.00, 58.28 } },
    { value = 30, rotation = { 270.00, 0.00, 180.00 } },
    { value = 27, rotation = { 54.00, 0.00, 238.28 } },
    { value = 21, rotation = { 0.00, 0.00, 90.00 } },
    { value = 25, rotation = { 54.00, 0.00, 121.72 } },
    { value = 23, rotation = { 330.00, 0.00, 200.91 } },
    { value = 24, rotation = { 330.00, 0.00, 20.91 } },
    { value = 26, rotation = { 30.00, 0.00, 20.91 } },
    { value = 30, rotation = { 0.00, 0.00, 270.00 } },
    { value = 26, rotation = { 306.00, 0.00, 301.72 } },
    { value = 28, rotation = { 342.00, 0.00, 301.72 } },
    { value = 25, rotation = { 30.00, 0.00, 159.09 } },
    { value = 29, rotation = { 30.00, 0.00, 200.91 } },
    { value = 24, rotation = { 306.00, 0.00, 58.28 } },
    { value = 23, rotation = { 18.00, 0.00, 121.72 } },
    { value = 29, rotation = { 18.00, 0.00, 58.28 } },
    { value = 28, rotation = { 330.00, 0.00, 339.09 } },
    { value = 22, rotation = { 30.00, 0.00, 339.09 } },
    { value = 21, rotation = { 90.00, 0.00, 0.00 } },
    { value = 27, rotation = { 330.00, 0.00, 159.09 } },
    { value = 22, rotation = { 306.00, 0.00, 238.28 } },
}

-- Nickname of each gear die in the save, indexed by gear.
Dice.names = {
    "First Gear Dice",
    "Second Gear Dice",
    "Third Gear Dice",
    "Fourth Gear Dice",
    "Fifth Gear Dice",
    "Sixth Gear Dice",
}

return Dice
