-- Generated by tools/extract/gen_registry.py from maps.json; do not edit by hand.

local Maps = {}

Maps.list = {
    { id = "FDAustin", name = "Formula D: Austin", key = "Formula D: Austin", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262835411/1480887E772610169EE1DE9454E0E29F07394BBD/", thumb = "fD6Austin" },
    { id = "FDBaltimore", name = "Formula D: Baltimore", key = "Formula D: Baltimore", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262829636/67BB74395A04A9B0596033157461FC9C77BB55D9/", thumb = "fD4Baltimore" },
    { id = "FDBuddh", name = "Formula D: Buddh", key = "Formula D: Buddh", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262832180/147A3A167C17284615698923BC9B37E7897BFC6B/", thumb = "fd4Buddh" },
    { id = "FDChicago", name = "Formula D: Chicago", key = "Formula D: Chicago", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014238203/908BBF22412D68A0CED43D6DAB6F93E73DE97239/", thumb = "formulaD1Bchicago" },
    { id = "FDDocks", name = "Formula D: Docks", key = "Formula D: Docks", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014241911/4D5CB22E13E9C014858B43596DFE2A628DF8CC2B/", thumb = "formulaD3Adocksorg" },
    { id = "FDDocksAlt", name = "Formula D: Docks (Alt)", key = "Formula D: Docks (Alt)", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014243040/E383145AB9B72D56A3A480E10ECEC452C07709C8/", thumb = "formulaD3Adocksrev" },
    { id = "FDHockenheim", name = "Formula D: Hockenheim", key = "Formula D: Hockenheim", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014239414/7980D8F0867FB1439C017653462FDD9242670F9B/", thumb = "formulaD2Ahockenheimring" },
    { id = "FDMonaco", name = "Formula D: Monaco", key = "Formula D: Monaco", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014232538/CC3911BF378E3DA31959B56901F60A14B456A1FF/", thumb = "formulaD0Amonaco" },
    { id = "FDNevada", name = "Formula D: Nevada", key = "Formula D: Nevada", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262836221/0624D7A4BF64E7DB01F49C6576EB98CC67DA204C/", thumb = "fD6Nevada" },
    { id = "FDNewJersey", name = "Formula D: New Jersey", key = "Formula D: New Jersey", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262832692/A579B7C010410CC2ACAE93FFED9027C1B6159809/", thumb = "fD5NewJersey" },
    { id = "FDRaceCity", name = "Formula D: Race City", key = "Formula D: Race City", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014233913/FDDA7626CA3F65CFB21601577F05C7E2364E62C1/", thumb = "formulaD0Bracecityorg" },
    { id = "FDRaceCityAlt", name = "Formula D: Race City (Alt)", key = "Formula D: Race City (Alt)", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014235128/29D90BF72EF0F8797A30F5F2E39A5C725C1E711F/", thumb = "formulaD0Bracecityrev" },
    { id = "FDSebring", name = "Formula D: Sebring", key = "Formula D: Sebring", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014237078/FDC094E0C1FF2870B60554A293DC15414BAFCF8F/", thumb = "formulaD1Asebring" },
    { id = "FDSingapore", name = "Formula D: Singapore", key = "Formula D: Singapore", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014244002/1806D1182356A335F1EC9A740C4448939B37725E/", thumb = "formulaD3Bsingapore" },
    { id = "FDSotchi", name = "Formula D: Sotchi", key = "Formula D: Sotchi", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943920262833674/ABA03FB3E5F2BF59D754299BE2A17465616A5AF1/", thumb = "fD5Sotchi" },
    { id = "FDValencia", name = "Formula D: Valencia", key = "Formula D: Valencia", category = "formula_d", url = "https://steamusercontent-a.akamaihd.net/ugc/1014943781014240406/80F9F33ECB931991D025DB32A0D97DC61037450A/", thumb = "formulaD2Bvalencia" },
}

Maps.byId = {}
for _, m in ipairs(Maps.list) do
    Maps.byId[m.id] = m
end

--- All maps in one category, in display order.
function Maps.inCategory(category)
    local out = {}
    for _, m in ipairs(Maps.list) do
        if m.category == category then
            out[#out + 1] = m
        end
    end
    return out
end

--- Image URL for a map id, or nil if the id is unknown.
function Maps.urlOf(id)
    local m = Maps.byId[id]
    return m and m.url or nil
end

return Maps
